"""Decoy Generator entry point.

    .venv/bin/python -m generator.generate [--offline] [--personas N]

Fabricates a believable fake company for the deception grid:

  1. `config/company.yaml`  - the org definition, parseable by `core.config.load_company`
  2. `seed/generated/<doc path>` - fake document bodies, one file per document
  3. `seed/generated/canary_manifest.json` - CANARY-TOKEN -> document path

Two content sources exist (AI via the Anthropic SDK, and a deterministic offline
generator), but only the *content strings* differ: schema assembly, canary
embedding, and file writing all happen here so both paths produce identical
structure. With no `ANTHROPIC_API_KEY` the offline source runs and output is
byte-identical on every run.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
import uuid
import zlib
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from generator import ai, templates as T
from generator.offline import OfflineContentSource

DEFAULT_CONFIG_PATH = "config/company.yaml"
DEFAULT_SEED_DIR = "seed/generated"

# Base URL of the hub's canary callback. When a canaried document (or its
# companion beacon) is opened in an app that fetches remote resources, it calls
# GET {CALLBACK_BASE}/canary/<token> and the hub records a CRITICAL trip — the
# classic canarytoken mechanism. Override for a real off-network deployment.
CALLBACK_BASE = os.environ.get("CANARY_CALLBACK_BASE", "http://localhost:8000").rstrip("/")
MANIFEST_NAME = "canary_manifest.json"

HEADER = (
    "# GENERATED by `python -m generator.generate` -- do not edit by hand.\n"
    "# 100% synthetic decoy data for an authorised honeypot lab. No real\n"
    "# people, hosts, or credentials appear here. Regenerate to change it.\n"
)


@dataclass
class GenerationResult:
    """What a run produced. Handy for tests and for the CLI summary."""

    mode: str                                  # "ai" or "offline"
    config_path: Path
    seed_dir: Path
    manifest_path: Path
    documents: list[Path] = field(default_factory=list)
    canaries: dict[str, str] = field(default_factory=dict)   # token -> doc path
    warnings: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Canary tokens
# ---------------------------------------------------------------------------

def canary_token(seed: int, path: str) -> str:
    """A unique `CANARY-TOKEN:<uuid>` marker for one document.

    Built from `uuid` but seeded from (seed, path) so the whole generator stays
    reproducible; each document still gets its own distinct token.
    """
    rng = random.Random(seed ^ zlib.crc32(f"canary|{path}".encode()))
    token = uuid.UUID(int=rng.getrandbits(128), version=4)
    return f"{T.CANARY_PREFIX}{token}"


def _token_id(token: str) -> str:
    """The bare token id (uuid) for use in a callback URL path."""
    return token.split(":", 1)[-1]


def _callback_url(token: str) -> str:
    return f"{CALLBACK_BASE}/canary/{_token_id(token)}"


def _embed_canary(body: str, token: str, doc_type: str) -> str:
    """Append the canary marker + callback URL as a document-control line."""
    prefix = "# " if doc_type in ("csv", "spreadsheet") else ""
    line = (f"{prefix}document tracking ref: {token} "
            f"(verify at {_callback_url(token)} - document control, do not remove)")
    return body.rstrip("\n") + "\n\n" + line + "\n"


def _beacon_html(token: str, doc_path: str) -> str:
    """A companion HTML 'beacon': opening it in a browser fires the real canary
    callback via a tracking pixel. Mirrors how a booby-trapped Office doc phones
    home when opened off-network."""
    return (
        "<!doctype html><html><head><meta charset='utf-8'>"
        f"<title>{doc_path}</title></head><body>"
        f"<!-- canary {token} -->"
        f"<img src='{_callback_url(token)}' width='1' height='1' alt=''>"
        f"<p>Meridian Logistics &mdash; protected document preview.</p>"
        "</body></html>\n"
    )


# ---------------------------------------------------------------------------
# Output writing (shared by both content sources)
# ---------------------------------------------------------------------------

def _dump_yaml(spec: dict) -> str:
    """Serialise the company spec in the schema `core.config` expects."""
    ordered = {
        "company": spec["company"],
        "personas": spec["personas"],
        "hosts": spec["hosts"],
        "documents": spec["documents"],
    }
    body = yaml.safe_dump(
        ordered, sort_keys=False, default_flow_style=False,
        allow_unicode=True, width=100,
    )
    return HEADER + body


def write_output(
    spec: dict,
    source,
    config_path: Path,
    seed_dir: Path,
    seed: int,
) -> GenerationResult:
    """Write company.yaml, every document body, and the canary manifest."""
    result = GenerationResult(
        mode=getattr(source, "name", "offline"),
        config_path=config_path,
        seed_dir=seed_dir,
        manifest_path=seed_dir / MANIFEST_NAME,
    )

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(_dump_yaml(spec), encoding="utf-8")

    for doc in spec["documents"]:
        body = source.document_body(doc, spec).rstrip("\n") + "\n"
        out = seed_dir / doc["path"]
        out.parent.mkdir(parents=True, exist_ok=True)
        if doc.get("canary"):
            token = canary_token(seed, doc["path"])
            body = _embed_canary(body, token, doc.get("doc_type", "note"))
            result.canaries[token] = doc["path"]
            # Companion beacon: opening it in a browser fires the hub callback.
            beacon = out.with_name(out.name + ".beacon.html")
            beacon.write_text(_beacon_html(token, doc["path"]), encoding="utf-8")
            result.documents.append(beacon)
        out.write_text(body, encoding="utf-8")
        result.documents.append(out)

    manifest = {
        "company": spec["company"]["name"],
        "note": "CANARY-TOKEN -> document path (relative to this directory).",
        "tokens": result.canaries,
    }
    result.manifest_path.parent.mkdir(parents=True, exist_ok=True)
    result.manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    result.warnings.extend(getattr(source, "errors", []))
    return result


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

def build_source(use_ai: bool | None, n_personas: int, seed: int | None):
    """Pick a content source. `use_ai=None` means 'AI if a key is set'."""
    want_ai = ai.available() if use_ai is None else use_ai
    if want_ai:
        try:
            return ai.AIContentSource(n_personas=n_personas, seed=seed)
        except Exception as exc:  # noqa: BLE001 - no SDK/key -> offline
            print(f"[generator] AI source unavailable ({exc}); using offline.",
                  file=sys.stderr)
    return OfflineContentSource(n_personas=n_personas, seed=seed)


def generate(
    config_path: str | Path = DEFAULT_CONFIG_PATH,
    seed_dir: str | Path = DEFAULT_SEED_DIR,
    use_ai: bool | None = None,
    n_personas: int = 5,
    seed: int | None = None,
) -> GenerationResult:
    """Generate the whole decoy corpus. Output paths are injectable for tests."""
    source = build_source(use_ai, n_personas, seed)
    spec = source.company_spec()
    return write_output(
        spec, source,
        config_path=Path(config_path),
        seed_dir=Path(seed_dir),
        seed=T.SEED if seed is None else seed,
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="generator.generate",
        description="Fabricate a fake company (config + decoy docs + canaries).",
    )
    ap.add_argument("--config", default=DEFAULT_CONFIG_PATH,
                    help=f"company.yaml output path (default: {DEFAULT_CONFIG_PATH})")
    ap.add_argument("--seed-dir", default=DEFAULT_SEED_DIR,
                    help=f"document output directory (default: {DEFAULT_SEED_DIR})")
    ap.add_argument("--personas", type=int, default=5, choices=[4, 5, 6],
                    help="number of personas to generate (default: 5)")
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--offline", action="store_true",
                      help="force the deterministic offline generator")
    mode.add_argument("--ai", action="store_true",
                      help="force the AI generator (needs ANTHROPIC_API_KEY)")
    args = ap.parse_args(argv)

    use_ai = True if args.ai else (False if args.offline else None)
    res = generate(
        config_path=args.config, seed_dir=args.seed_dir,
        use_ai=use_ai, n_personas=args.personas,
    )

    print(f"[generator] mode      : {res.mode}")
    print(f"[generator] config    : {res.config_path}")
    print(f"[generator] documents : {len(res.documents)} under {res.seed_dir}")
    print(f"[generator] canaries  : {len(res.canaries)} -> {res.manifest_path}")
    for w in res.warnings:
        print(f"[generator] warning   : {w}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
